set_license("GPL-3.0")
set_languages("cxx17")
add_rules("mode.debug", "mode.release")
add_requires("catch2")
add_requires("eigen")
add_requires("pytype")

target("tests")
    set_kind("binary")
    add_packages("catch2")
    add_files("tests/*.cpp|benchmark.cpp")

target("examples")
    set_kind("binary")
    add_packages("eigen")
    add_packages("pytype")
    add_files("examples/*.cpp")

target("benchmark")
    set_kind("binary")
    add_packages("catch2")
    add_packages("pytype")
    add_files("tests/benchmark.cpp")
